import { Router } from 'express';
import mutateRouter from './mutate.js';
import versionRouter from './version.js';
import processTemplateStepsRouter from './processTemplateSteps.js';
import stockRouter     from './stock.js';
import bomRouter       from './bom.js';
import itemsRouter     from './items.js';
import orderItemsRouter from './orderItems.js';
import resourcesRouter from './resources.js';
import operationsRouter from './operations.js';
import flowStepsRouter  from './flowSteps.js';
import codegenRouter   from './codegen.js';
import formulaRouter   from './formula.js';
import searchRouter    from './search.js';
import tasksRouter     from './tasks.js';
import machineStateRouter from './machineState.js';
import buffersRouter   from './buffers.js';
import reconciliationRouter from './reconciliation.js';
import analyticsRouter   from './analytics.js';
import navCountsRouter   from './navCounts.js';
import pulseRouter       from './pulse.js';
import marksRouter       from './marks.js';
import shiftLogRouter    from './shiftLog.js';
import workersRouter     from './workers.js';

const router = Router();

router.get('/health', (req, res) => res.json({ ok: true, app: 'fab_erp' }));

router.use(mutateRouter);
router.use(versionRouter);
router.use(processTemplateStepsRouter);
router.use(stockRouter);
router.use(bomRouter);
router.use(itemsRouter);
router.use(orderItemsRouter);
router.use(resourcesRouter);
router.use(operationsRouter);
router.use(flowStepsRouter);
router.use(codegenRouter);
router.use(formulaRouter);
router.use(searchRouter);
router.use(tasksRouter);
router.use(machineStateRouter);
router.use(buffersRouter);
router.use(reconciliationRouter);
router.use(analyticsRouter);
router.use(navCountsRouter);
router.use(pulseRouter);
router.use(marksRouter);
router.use(shiftLogRouter);
router.use(workersRouter);

export default router;
