/**
 * render/responsibilityProfile.js — the Employee Responsibility Profile writers,
 * DOCX and PDF. (Plan §17.3, §17.4.)
 *
 * ── WHAT THIS DOCUMENT IS FOR ─────────────────────────────────────────────
 * It is the one an SME actually hands to a person, and its whole job is to make
 * "Ram Babu does three jobs" legible on one page. So it is ordered by WORK
 * ASSIGNMENT, not by role and not by department: one block per assignment, each
 * with its own role, position, allocation, work contexts, managers and resolved
 * content. A profile ordered any other way has to merge three jobs into one list
 * and immediately loses which duty belongs to which hat.
 *
 * ── THE MANAGERS ARE A SET, WITH SCOPES ───────────────────────────────────
 * Plan §2 rule 9. `reportingResolver` returns every relationship live on the
 * date — a primary line inherited from the position, a functional or dotted line
 * recorded on the assignment, each with its scope ("statutory compliance", one
 * machine, one project) — and this renderer prints all of them, labelled formal
 * or actual. It never picks one and calls it "the manager". Where an assignment
 * row replaced an inherited formal one, the formal row is printed too, under
 * "The chart also says", because "the design says X, this person answers to Y" is
 * information and not noise.
 *
 * ── ONLY THE SNAPSHOT ─────────────────────────────────────────────────────
 * As in roleJd.js: no `db` parameter exists in this file, so a historical
 * profile cannot re-read today's model even by accident.
 *
 * ── AND WHAT IS NOT HERE ──────────────────────────────────────────────────
 * No statutory identifiers, no date of birth, no address, no photo. The snapshot
 * does not carry them (documentService says why), so this file cannot print them.
 */
import { Document, Packer, Paragraph, TextRun, BorderStyle } from 'docx';
import {
  // The content block is shared with the Role JD on purpose: a responsibility
  // must read identically whether it is printed in a JD or in a person's file.
  contentBlocksDocx, exceptionBlocksDocx, writeContentPdf, writeExceptionsPdf,
  newPdf, pdfKit, pdfBuffer, writeHeaderPdf, writeFooterPdf,
  reportingLine, lineOf, layerChain, sectionOf, titleCase, factTable, h1, h2, body, small, italic, bullet, spacer,
} from './roleJd.js';

const GREY = '666666';
const RULE = 'DDDDDD';

/**
 * "Admin Head/Manager — 100% · primary". The assignment's one-line identity.
 *
 * `startsLater` is spelled out rather than left to the From row: a profile dated
 * before a job begins must not read as if the person were already doing it.
 */
function assignmentHeading(a, index) {
  const bits = [`${index + 1}. ${a.roleTitle ?? a.assignmentTitle ?? `Assignment ${a.id}`}`];
  const meta = [];
  if (a.allocationPercent != null) meta.push(`${a.allocationPercent}%`);
  if (a.isPrimary) meta.push('primary');
  if (a.status && a.status !== 'ACTIVE') meta.push(titleCase(a.status));
  if (a.startsLater) meta.push(`not started yet, begins ${a.effectiveFromText ?? a.effectiveFrom}`);
  return meta.length ? `${bits[0]} — ${meta.join(' · ')}` : bits[0];
}

const contextLine = (c) => `${c.name}${c.type ? ` (${titleCase(c.type)})` : ''}${c.isPrimary ? ' — primary' : ''}`;

/* ══════════════════════════════════════════════════════════════════════════
 * DOCX
 * ══════════════════════════════════════════════════════════════════════════ */

function headerBlocksDocx(snapshot) {
  return [
    new Paragraph({
      children: [new TextRun({ text: snapshot.company?.name ?? '', bold: true, size: 20, color: GREY })],
      spacing: { after: 40 },
    }),
    new Paragraph({
      children: [new TextRun({ text: snapshot.title, bold: true, size: 32 })],
      spacing: { after: 40 },
    }),
    new Paragraph({
      children: [new TextRun({ text: snapshot.subtitle ?? '', size: 20, color: GREY })],
      spacing: { after: 120 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: RULE, space: 4 } },
    }),
    small([
      `As at ${snapshot.asOfText ?? snapshot.asOf}`,
      snapshot.generatedBy?.name ? `generated by ${snapshot.generatedBy.name}` : null,
      `template ${snapshot.templateVersion}`,
    ].filter(Boolean).join(' · ')),
    italic(snapshot.honestyNote),
  ];
}

export async function renderProfileDocx(snapshot) {
  const { employee, assignments, summary, excludedAssignments = [] } = snapshot;
  const children = [
    ...headerBlocksDocx(snapshot),
    factTable([
      ['Employee code', employee.employeeCode],
      ['Name', employee.fullName],
      ['Joined', employee.dateOfJoiningText ?? employee.dateOfJoining],
      ['Employment', [titleCase(employee.employmentType), employee.contractorName ? `via ${employee.contractorName}` : null]
        .filter(Boolean).join(' · ')],
      ['Status', titleCase(employee.employmentStatus)],
      ['Work assignments', `${summary.assignments}`],
      ['Time committed', `${summary.totalAllocationPercent}%${summary.overAllocated ? ' — over 100%, which is a fact about the workload, not an error' : ''}`],
    ]),
  ];

  const assignmentSection = sectionOf(snapshot.sections, 'assignments');
  if (!assignments.length) {
    children.push(h1(assignmentSection.heading));
    children.push(italic(assignmentSection.note ?? 'No open work assignment.'));
  }

  assignments.forEach((entry, i) => {
    const { assignment: a, reporting, content, sections } = entry;
    children.push(h1(assignmentHeading(a, i)));
    children.push(factTable([
      ['Role', [a.roleCode, a.roleTitle].filter(Boolean).join(' · ')],
      ['Position', a.positionCode ? [a.positionCode, a.positionTitle].filter(Boolean).join(' · ') : 'No position — the work is real without a sanctioned seat'],
      ['Department', a.departmentName],
      ['Location', a.locationName],
      ['Shift', a.shiftCode ? `${a.shiftCode}${a.shiftName ? ` — ${a.shiftName}` : ''}` : null],
      ['Allocation', a.allocationText],
      ['From', a.effectiveFromText ?? a.effectiveFrom],
      ['Status', titleCase(a.status)],
    ]));

    // Contexts: machines and areas are never managers (plan §2 rule 3).
    const ctxSection = sectionOf(sections, 'contexts');
    children.push(h2(ctxSection.heading));
    if (!a.contexts.length) children.push(italic(ctxSection.note ?? 'Not recorded yet.'));
    else for (const c of a.contexts) children.push(bullet(contextLine(c)));

    // THE SET. Never flattened.
    const repSection = sectionOf(sections, 'reporting');
    children.push(h2(repSection.heading));
    children.push(small('Every manager for this work, with the part of it each one covers. A dotted or functional line stands beside a primary one; it does not replace it.'));
    if (!reporting.relationships.length) children.push(italic(repSection.note ?? 'Not recorded yet.'));
    else for (const rel of reporting.relationships) children.push(bullet(reportingLine(rel)));

    if (reporting.superseded?.length) {
      children.push(body('The chart also says', { bold: true, size: 20 }));
      children.push(small('Formal lines this person\'s own reporting replaced. Kept visible on purpose.'));
      for (const rel of reporting.superseded) children.push(bullet(reportingLine(rel)));
    }

    // The same content block the JD prints, one level down.
    children.push(...contentBlocksDocx(content, sections, 'h2'));

    if (content.authorities.length) {
      children.push(h2(sectionOf(sections, 'authorities').heading));
      for (const r of content.authorities) children.push(bullet(lineOf(r)));
    }

    children.push(...exceptionBlocksDocx(content, sections, 'h2'));
    children.push(small(`Content resolved through ${layerChain(content.layers)}.`));
    children.push(spacer());
  });

  if (excludedAssignments.length) {
    children.push(h1('Work this person no longer holds'));
    children.push(small('Listed so the profile is not read as a complete history.'));
    for (const e of excludedAssignments) {
      children.push(bullet(`${e.roleTitle ?? `Assignment ${e.id}`} — ${e.why}`));
    }
  }

  children.push(spacer());
  children.push(small(`This document is a snapshot of the record as it stood on ${snapshot.asOfText ?? snapshot.asOf}. `
    + 'It was generated from the stored snapshot and does not change when the role, position or assignment is later edited.'));

  const doc = new Document({
    creator: snapshot.company?.name ?? 'CF HRMS',
    title: snapshot.title,
    description: snapshot.subtitle ?? '',
    sections: [{ properties: {}, children }],
  });
  return Packer.toBuffer(doc);
}

/* ══════════════════════════════════════════════════════════════════════════
 * PDF
 * ══════════════════════════════════════════════════════════════════════════ */

export async function renderProfilePdf(snapshot) {
  const { employee, assignments, summary, excludedAssignments = [] } = snapshot;
  const doc = newPdf(snapshot);
  const kit = pdfKit(doc);

  writeHeaderPdf(kit, snapshot);
  kit.facts([
    ['Employee code', employee.employeeCode],
    ['Name', employee.fullName],
    ['Joined', employee.dateOfJoiningText ?? employee.dateOfJoining],
    ['Employment', [titleCase(employee.employmentType), employee.contractorName ? `via ${employee.contractorName}` : null]
      .filter(Boolean).join(' · ')],
    ['Status', titleCase(employee.employmentStatus)],
    ['Work assignments', `${summary.assignments}`],
    ['Time committed', `${summary.totalAllocationPercent}%${summary.overAllocated ? ' — over 100%, which is a fact about the workload, not an error' : ''}`],
  ]);

  const assignmentSection = sectionOf(snapshot.sections, 'assignments');
  if (!assignments.length) {
    kit.heading(assignmentSection.heading, 1);
    kit.note(assignmentSection.note ?? 'No open work assignment.');
  }

  assignments.forEach((entry, i) => {
    const { assignment: a, reporting, content, sections } = entry;
    kit.heading(assignmentHeading(a, i), 1);
    kit.facts([
      ['Role', [a.roleCode, a.roleTitle].filter(Boolean).join(' · ')],
      ['Position', a.positionCode ? [a.positionCode, a.positionTitle].filter(Boolean).join(' · ') : 'No position — the work is real without a sanctioned seat'],
      ['Department', a.departmentName],
      ['Location', a.locationName],
      ['Shift', a.shiftCode ? `${a.shiftCode}${a.shiftName ? ` — ${a.shiftName}` : ''}` : null],
      ['Allocation', a.allocationText],
      ['From', a.effectiveFromText ?? a.effectiveFrom],
      ['Status', titleCase(a.status)],
    ]);

    const ctxSection = sectionOf(sections, 'contexts');
    kit.heading(ctxSection.heading, 2);
    if (!a.contexts.length) kit.note(ctxSection.note ?? 'Not recorded yet.');
    else for (const c of a.contexts) kit.bullet(contextLine(c));

    const repSection = sectionOf(sections, 'reporting');
    kit.heading(repSection.heading, 2);
    kit.smallText('Every manager for this work, with the part of it each one covers. A dotted or functional line stands beside a primary one; it does not replace it.');
    if (!reporting.relationships.length) kit.note(repSection.note ?? 'Not recorded yet.');
    else for (const rel of reporting.relationships) kit.bullet(reportingLine(rel));

    if (reporting.superseded?.length) {
      kit.text('The chart also says', { size: 9.5, font: 'Helvetica-Bold', after: 2 });
      kit.smallText('Formal lines this person\'s own reporting replaced. Kept visible on purpose.');
      for (const rel of reporting.superseded) kit.bullet(reportingLine(rel));
    }

    writeContentPdf(kit, content, sections, 2);

    if (content.authorities.length) {
      kit.heading(sectionOf(sections, 'authorities').heading, 2);
      for (const r of content.authorities) kit.bullet(lineOf(r));
    }

    writeExceptionsPdf(kit, content, sections, 2);
    kit.smallText(`Content resolved through ${layerChain(content.layers)}.`);
  });

  if (excludedAssignments.length) {
    kit.heading('Work this person no longer holds', 1);
    kit.smallText('Listed so the profile is not read as a complete history.');
    for (const e of excludedAssignments) kit.bullet(`${e.roleTitle ?? `Assignment ${e.id}`} — ${e.why}`);
  }

  writeFooterPdf(kit, snapshot);
  return pdfBuffer(doc);
}

export default { renderProfileDocx, renderProfilePdf };
